### ISSUE TITLE
Internet Explorer display issue

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Functionality#13]
When accessing DSB GUI via Internet Explorer and creating any instruments with optional input fields – if the user removes any of the optional fields using the Properties button and then selects the removed fields back for display – the fields are no longer displayed.

**Workaround**: Click Create button to re-select the template and correct the choice of the optional fields. 

**Impact**:
- GUI only
- Internet Explorer
- Instruments with optional input fields

**Environment**:
- UAT, Production.

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in Production on 24/Nov/18
