### ISSUE TITLE
Logout is required after using Password Change in DSB GUI

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Functionality#17]
Users are required to logout and login back into the DSB GUI following a change of password. Doing so will ensure that users continue to have access to the full suite of DSB GUI functionality. 
Please note that failure to log out and log back in following a successful password change can result in invalid search results and/or create operations if applicable when using the GUI.
The DSB will be introducing a fix to prompt the user to re-login, until this is implemented, the users are asked to remember to re-login after changing password.

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in UAT

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in UAT 12/May/18

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in Production 30/June/18
