### ISSUE TITLE
Normalization not used for FX Option searches

### ISSUE THREAD

**Issue by s13n4** [ANNA-DSB/Functionality#4]
Anna DSB normalizes data to ensure only one ISIN can be generated for a put or call option on a common currency pair. That's ok.
For example I created FX Option as PUTO EURO EUR/PLN (ISIN EZBG4KY8JK32)
I can search for this characteristic and I will get the ISIN EZBG4KY8JK32.
`/Header/AssetClass:Foreign_Exchange && /Header/InstrumentType:Option && /Header/UseCase:Vanilla_Option && /Attributes/ExpiryDate:2017-11-02 && /Attributes/NotionalCurrency:EUR && /Attributes/OptionType:PUTO && /Attributes/OptionExerciseStyle:EURO && /Attributes/DeliveryType:PHYS && /Attributes/OtherNotionalCurrency:PLN`

If want to create ISIN for CALL EURO PLN/EUR, I will get the same EZBG4KY8JK32. That's correct based on 7.4  FX Option Normalization rule.
But when I try to search for this characteristic:
`/Header/AssetClass:Foreign_Exchange && /Header/InstrumentType:Option && /Header/UseCase:Vanilla_Option && /Attributes/ExpiryDate:2017-11-02 && /Attributes/NotionalCurrency:PLN && /Attributes/OptionType:CALL && /Attributes/OptionExerciseStyle:EURO && /Attributes/DeliveryType:PHYS && /Attributes/OtherNotionalCurrency:EUR`

Anna DSB returns ZERO Results. 

Can you confirm, that this feature (search) is working as intended? In my opinion is not.

**Comment by AnnaDSBTechnicalSupport** [comment]
The search takes your values literally and does not apply normalization and normalization is only done during the creation of the record. 

Inspecting the record EZBG4KY8JK32, the NotionalCurrency is EUR and OtherNotionalCurrency is PLN so the search result/s you encountered are expected.  

Going forward, please reach to us via sending an email to technical.support@anna-dsb.com if you have further concerns.
