### ISSUE TITLE
When search conditions include Equity and Commodity products: products with Proprietary indices will not be returned in the search results

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Functionality#8]
When search conditions include Equity, Credit or Commodity products and specifically those products with Proprietary indices, search results might inaccurately show number of records returned, as in a certain edge case Proprietary indices might get included in the total search results count while Prop indices themselves are not returned in the search results.

**_Impact:_**
**Environment:** UAT

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in UAT 12/May/18

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in Production 30/June/18
