### ISSUE TITLE
Unable to search for a date range in LastUpdateDateTime

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Functionality#9]
A search for a date range in LastUpdateDateTime returns inaccurate results, e.g
a syntactically correct search query for records updated today, also returns records that are updated prior to today.
Search by lastupdatedatetime only works when specifying an exact timestamp, 
e.g. /ISIN/LastUpdateDateTime:"2017-11-05T08:57:43" and returns inaccurate results for a date range.
**_Impact_**
**Environment**: UAT, Production

**Comment by AnnaDSBTechnicalSupport** [comment]
This functionality has been in place in the UAT environment since 28th April 2018.

**Comment by AnnaDSBTechnicalSupport** [comment]
Functionality has been completely deployed in Production Environment on 11th October 2020
